{
 "title": "F1 Platform - Status Dashboard",
 "description": "Page showing status of particular F1 Platform Components",
 "tags": [ "f1-platform" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Classify ML Model - FastAPI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"classification-model-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recognize ML Model - FastAPI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"recognition-model-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Explore - Pygwalker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"data-dashboard-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Academy - Dash",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"driver-dashboard-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Models - MLFlow",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"mlflow-dashboard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage - MinIO",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"minio-s3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring - Prometheus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregate - Grafana",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"f1-platform\", container=\"grafana-sc-dashboard\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}