apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: prometheus-ingress
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    labels:
      app: f1-platform
      component: prometheus
spec:
  tls:
    - hosts:
      - monitoring.f1-platform.zawalich.pl
      secretName: echo-tls
  rules:
    - host: monitoring.f1-platform.zawalich.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: grafana-ingress
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    labels:
      app: f1-platform
      component: grafana
spec:
  tls:
    - hosts:
      - aggregate.f1-platform.zawalich.pl
      secretName: echo-tls
  rules:
    - host: aggregate.f1-platform.zawalich.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000                  